Models/MeetingInfo.cs
namespace MeetingApp.Models
{
    public class MeetingInfo
    {
        public int Id { get; set; }
        public string? Location { get; set; }
        public DateTime Date { get; set; }
        public int NumberOfPeople { get; set; }
    }
}

Models/Repository.cs
namespace MeetingApp.Models
{
    public static class Repository
    {
        private static List<UserInfo> _users = new();

        static Repository()
        {
            _users.Add(new UserInfo() { Id = 1, Name = "Ali", Email = "ali@info.com", Phone = "11111", WillAttend = true });
            _users.Add(new UserInfo() { Id = 2, Name = "Ahmet", Email = "ahmet@info.com", Phone = "22222", WillAttend = false });
            _users.Add(new UserInfo() { Id = 3, Name = "Mehmet", Email = "mehmet@info.com", Phone = "33333", WillAttend = true });
        }

        public static List<UserInfo> Users
        {
            get
            {
                return _users;
            }
        }

        public static void CreateUser(UserInfo user)
        {
            user.Id = Users.Count + 1;
            _users.Add(user);
        }

        public static UserInfo? GetById(int id)
        {
            return _users.FirstOrDefault(user => user.Id == id);
        }
    }
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
    public class UserInfo
    {
        public int Id { get; set; }

        [Required]
        public string? Name { get; set; }

        [Required]
        public string? Phone { get; set; }

        [Required]
        [EmailAddress]
        public string? Email { get; set; }

        [Required]
        public bool? WillAttend { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            int UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
            int saat = DateTime.Now.Hour;

            ViewData["Selamlama"] = saat > 12 ? "Iyi gunler" : "Gunaydin";

            var meetingInfo = new MeetingInfo()
            {
                Id = 1,
                Location = "Istanbul, Abc Kongre Merkezi",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = UserCount
            };


            return View(meetingInfo);
        }
    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class MeetingController : Controller
    {
        [HttpGet]
        public IActionResult Apply()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Apply(UserInfo model)
        {
            if (ModelState.IsValid)
            {
                Repository.CreateUser(model);
                ViewBag.UserCount = Repository.Users.Where(info => info.WillAttend == true).Count();
                return View("Thanks", model);
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public IActionResult List()
        {
            return View(Repository.Users);
        }

        public IActionResult Details(int id)
        {
            return View(Repository.GetById(id));
        }
    }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
ViewBag.Title = "Bavuru Formu";
Layout = "_Layout2";
}
<main class="text-center">
    <h1 class="h4">@ViewData["Selamlama"]</h1>
    <p>Toplanti katilim durumunuzu buldiriniz</p>

    <div class="card my-2">
        <ul class="list-group list-group-flush">
            <li class="list-group-item">@Model.Location</li>
            <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss")</li>
            <li class="list-group-item">@Model.NumberOfPeople Katilimci</li>
        </ul>
    </div>

    <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply">Basvuru yap</a>
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
ViewBag.Title = "Toplanti Basvuru";
}
<h1 class="h4 text-center">Toplanti katilim formu</h1>
<form method="post" action="/Meeting/Apply" novalidate>
    <div asp-validation-summary="All"></div>
    <div class="mb-3">
        <label asp-for="Name">Isim Soyisim</label>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Phone">Telefon</label>
        <input asp-for="Phone" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="Email">Eposta</label>
        <input asp-for="Email" class="form-control">
    </div>
    <div class="mb-3">
        <label asp-for="WillAttend">Katilim Durumu</label>
        <select asp-for="WillAttend" class="form-select">
            <option value="">Seciniz</option>
            <option value="true">Evet, Katilacagim</option>
            <option value="false">Hayir, Katilmayacagim</option>
        </select>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
ViewBag.Title = "Basvuru Detayi";
}

@{
var className = @Model.WillAttend == true ? "primary" : "danger";
}

<main class="text-center">
    <h1 class="h4">Basvuru Detayi</h1>
    <p>
        <span class="badge text-bg-@className">
            @if(Model.WillAttend == true){
            <text>Katiliyor</text>
            }else{
            <text>
                Katilmiyor
            </text>
            }
        </span>
    </p>
    <p>Isim: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Phone: @Model.Phone</p>
    <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katilimci Listesi</a>
</main>

Views/Meeting/Index.cshtml
@{
ViewBag.Title = "Toplanti Ozeti";
}
<main class="text-center">
    <h1 class="h4">Toplanti ozeti</h1>
    <p>Toplantiya sizinle birlikte 20 kisi katiliyor</p>
    <a class="btn btn-sm btn-outline-primary" href="#">Katilimcilari listele</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
    @{
    ViewBag.Title = "Toplanti Katilim Listesi";
    }
    <main class="text-center">
        <h1 class="h4">Toplantiya Katilim Listesi</h1>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <td>Ad</td>
                    <td>Email</td>
                    <td>Katilim Durumu</td>
                </tr>
            </thead>
            <tbody>
                @{ int i = 0; }
                @foreach(var user in Model){
                var durum = user.WillAttend == true ? "Evet":"Hayir";
                var className = user.WillAttend == true ? "table-success":"table-danger";
                if(user.WillAttend == true){
                i++;
                }
                <tr class="@className">
                    <td>@user.Name</td>
                    <td>@durum</td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <div class="card">
            <div class="card-body">
                <span>Katilimci Sayisi: @i</span>
            </div>
        </div>
    </main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
ViewBag.Title = "Basvuru Durumu";
}
<main class="text-center">
    <h1 class="h4">Basvuru Durumu</h1>

    @if(Model.WillAttend == true){
    <p>Tesekkurler, @Model.Name toplantiya sizinle birlikte @ViewBag.UserCount kisi katiliyor</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katilimcilari listele</a>
    } else {
    <p>@Model.Name, katilmadigindan dolayi uzgunuz</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Basvuru Formu</a>

    }
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css">
    <title>@ViewBag.Title - MeetingApp</title>
</head>

<body>
    <div class="bg-primary text-white p-2 text-center">
        Meeting App
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
    <title>@ViewBag.Title - MeetingApp</title>
</head>
<body>
    <div class="bg-danger text-white p-2 text-center">
        Meeting App
    </div>
    <div class="container mt-3">
        <div class="row">
            <div class="col-lg-6 mx-auto text-center">
                <div class="card">
                    <div class="card-body">
                        @RenderBody()
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>